import React from 'react';
import { Row, Col, Button } from 'reactstrap';
var LandingPageBody = function (props) {
    return (React.createElement("div", { className: "main" },
        React.createElement("div", { className: "section text-center" },
            React.createElement(Row, null,
                React.createElement(Col, { className: "ml-auto mr-auto", md: "8" },
                    React.createElement("h2", { className: "title" }, "Let's talk product"),
                    React.createElement("h5", { className: "description" }, "This is the paragraph where you can write more details about your product. Keep you user engaged by providing meaningful information. Remember that by this time, the user is curious, otherwise he wouldn't scroll to get here. Add a button if you want the user to see more."),
                    React.createElement("br", null),
                    React.createElement(Button, { className: "btn-round", color: "info", href: "#", onClick: function (e) { return e.preventDefault(); } }, "See Details"))),
            React.createElement("br", null),
            React.createElement("br", null),
            React.createElement(Row, null,
                React.createElement(Col, { md: "3" },
                    React.createElement("div", { className: "info" },
                        React.createElement("div", { className: "icon icon-info" },
                            React.createElement("i", { className: "nc-icon nc-album-2" })),
                        React.createElement("div", { className: "description" },
                            React.createElement("h4", { className: "info-title" }, "Beautiful Gallery"),
                            React.createElement("p", { className: "description" }, "Spend your time generating new ideas. You don't have to think of implementing."),
                            React.createElement(Button, { className: "btn-link", color: "info", href: "#" }, "See more")))),
                React.createElement(Col, { md: "3" },
                    React.createElement("div", { className: "info" },
                        React.createElement("div", { className: "icon icon-info" },
                            React.createElement("i", { className: "nc-icon nc-bulb-63" })),
                        React.createElement("div", { className: "description" },
                            React.createElement("h4", { className: "info-title" }, "New Ideas"),
                            React.createElement("p", null, "Larger, yet dramatically thinner. More powerful, but remarkably power efficient."),
                            React.createElement(Button, { className: "btn-link", color: "info", href: "#" }, "See more")))),
                React.createElement(Col, { md: "3" },
                    React.createElement("div", { className: "info" },
                        React.createElement("div", { className: "icon icon-info" },
                            React.createElement("i", { className: "nc-icon nc-chart-bar-32" })),
                        React.createElement("div", { className: "description" },
                            React.createElement("h4", { className: "info-title" }, "Statistics"),
                            React.createElement("p", null, "Choose from a veriety of many colors resembling sugar paper pastels."),
                            React.createElement(Button, { className: "btn-link", color: "info", href: "#" }, "See more")))),
                React.createElement(Col, { md: "3" },
                    React.createElement("div", { className: "info" },
                        React.createElement("div", { className: "icon icon-info" },
                            React.createElement("i", { className: "nc-icon nc-sun-fog-29" })),
                        React.createElement("div", { className: "description" },
                            React.createElement("h4", { className: "info-title" }, "Delightful design"),
                            React.createElement("p", null, "Find unique and handmade delightful designs related items directly from our sellers."),
                            React.createElement(Button, { className: "btn-link", color: "info", href: "#" }, "See more"))))))));
};
export default LandingPageBody;
